// <auto-generated />
using System;
using DTI.VoTech.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DTI.VoTech.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190528222644_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DTI.VoTech.Models.Techshot", b =>
                {
                    b.Property<int>("TechshotId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataInicio");

                    b.Property<int?>("TemasTemaId");

                    b.HasKey("TechshotId");

                    b.HasIndex("TemasTemaId");

                    b.ToTable("Techshots");
                });

            modelBuilder.Entity("DTI.VoTech.Models.Tema", b =>
                {
                    b.Property<int>("TemaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<string>("Titulo");

                    b.Property<int>("Votos");

                    b.HasKey("TemaId");

                    b.ToTable("Temas");
                });

            modelBuilder.Entity("DTI.VoTech.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("NomeUsuario");

                    b.Property<string>("Senha");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DTI.VoTech.Models.Votacao", b =>
                {
                    b.Property<int>("VotacaoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataInicio");

                    b.Property<DateTime>("Duracao");

                    b.Property<int?>("TemaVencedorTemaId");

                    b.HasKey("VotacaoId");

                    b.HasIndex("TemaVencedorTemaId");

                    b.ToTable("Votacoes");
                });

            modelBuilder.Entity("DTI.VoTech.Models.Techshot", b =>
                {
                    b.HasOne("DTI.VoTech.Models.Tema", "Temas")
                        .WithMany()
                        .HasForeignKey("TemasTemaId");
                });

            modelBuilder.Entity("DTI.VoTech.Models.Votacao", b =>
                {
                    b.HasOne("DTI.VoTech.Models.Tema", "TemaVencedor")
                        .WithMany()
                        .HasForeignKey("TemaVencedorTemaId");
                });
#pragma warning restore 612, 618
        }
    }
}
